ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-lepton_masses'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_100 = ', GC_100
